### ISSUE TITLE
Update to GitHub Actions

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/helm-chart#22]
This repo is a little out of date. Looks like the Travis CI no longer works so we should migrate to GitHub actions.

**Comment by jacobtomlinson** [comment]
@D3N14L you've been super helpful here, any interest in helping out with this?

**Comment by D3N14L** [comment]
I´ll check what I can do as soon as I find the time. 👍

**Comment by D3N14L** [comment]
@jacobtomlinson I think this issue can be closed as done now :-)
